api_version: 1
runtime: python27
threadsafe: false
instance_class: F1

handlers:

- url: /assets
  static_dir: dist/assets
  expiration: 1d
  secure: always

- url: /(.*\.(js|css|map))$
  static_files: dist/\1
  upload: dist/(.*\.(js|css|map))$
  expiration: 364d
  secure: always

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  expiration: 1s
  secure: always

skip_files:
- ^(?!dist)