version: '3.3'
services:
  app:
    image: klutzer/personal-website:latest
    restart: always
    environment:
      PORT: '8080'
      DB_HOST: 'postgres'
      DB_NAME: 'postgres'
      DB_PASSWORD: 'JWUyMfDMGIJpgxQ2a0/9henWzWqRGYuPygbUxtEnIhM='
      DB_USER: 'root'
      PING_HOST: 'hc-ping.com/d1fb6482-4f57-4854-9716-3a376334f085'
      VERSION: '4.1.0'
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    expose:
      - '8080'
  postgres:
    image: arm64v8/postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: JWUyMfDMGIJpgxQ2a0/9henWzWqRGYuPygbUxtEnIhM=
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - personal-website-postgress-data:/var/lib/postgresql
volumes:
  personal-website-postgress-data: