name: DockerImage-CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    # Login to our Docker registry
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Setup node and a cache for dependencies
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    # Setup go and a cache for dependencies
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    # Install Just
    - uses: extractions/setup-just@v3
      name: Install Just
      with:
        just-version: '1.40.0'

    # Build Container
    - name: Build the Docker image
      run: just build

    # Push Container
    - name: Push the Docker image
      run: just push